apiVersion: plumber.ugent.be/v1alpha1
kind: TopologyPart
metadata:
  name: my-first-topo-scientist
spec:
  processors:
    transformer-0:
      inputFrom: kafka-ingress
      code: "image;verstraetebert/plumber-greeter:v0.0.1"
      env:
        - name: MSG
          value: "Hello from transformer-0!"
      sinkBindings: kafka-egress
      maxScale: 10
